services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=medium
      - ASR_ENGINE=openai_whisper
    volumes:
      - whisper_models:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - WHISPER_HOST=http://whisper:9000
      - LOG_LEVEL=debug
    volumes:
      - speechsmith_logs:/var/log/speechsmith
    depends_on:
      - ollama
      - whisper
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BASE_API_URL=http://localhost:3001
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  ollama_data:
  whisper_models:
  speechsmith_logs:
